### ISSUE TITLE
Cleanup and add ROMs?

### ISSUE THREAD

**Issue by DerekTurtleRoe** [schibo/1964js#3]
So I think the ROMs directory is a little disorganized. A folder with public domain ROMs, then an "unofficial" folder seems to be redundant also.

My thought was that we take all the ROMs and then put them in one folder, and we make sure they are verified working and also name them appropriately. We could have folders, although the only ROMs we can use are homebrew and public domain/demoscene releases, which all kind of fall in the same category.

I have a repository of ROMs on GitHub, and we can add all those since all of them are public domain, homebrew, and demoscene releases. We can pick and choose individual ROMs, but why limit ourselves? 😄 

Let's discuss it before I implement anything.

**Comment by schibo** [comment]
Hi vgturtle127,
Interesting thought, but I don't think this is necessary. "unofficial" is to distinguish from official "good roms" which are standard in the community and I don't want to muddy the waters.

**Comment by DerekTurtleRoe** [comment]
@schibo When you say "good roms", are you talking about GoodSets, and if so, when you say "unofficial", do you mean ROM's found outside of that set? Just wanted to clarify.

**Comment by schibo** [comment]
Unofficial means I cleaned up the contents of the archive. The unzip library was confused as to what file in the archive to load, which is something that should probably be addressed separately.
