### ISSUE TITLE
Remove fragment.shader.backup

### ISSUE THREAD

**Issue by vgturtle127** [schibo/1964js#6]
We don't need backups, we have Git for that! :smile:

**Comment by vgturtle127** [comment]
After some investigation, there are minor differences in how the two documents are written.

The backup file has an additional return; after gl_FragColor = (a*p + b*m)/(a+b);

The backup file also has the following lines commented out:

//int tex0=3;
//int tex1=4;
//int env=7;
//int blend=2;
//int prim=5;
//int shade=6;

Whereas in the other (non-backup) file, those lines are not commented out and these lines are:

//tex0=3;
//tex1=4;
//env=7;
//blend=2;
//prim=5;
//shade=6;

It would be nice to know which was more correct or more complete, or which is used on the website.

Any help would be appreciated, @schibo ! :smiley:

**Comment by schibo** [comment]
gl_FragColor *= (a*p + b*m)/(a+b); is more correct and is what's on the website, but the fragment shader file overall is still very buggy.

The file is on the website here:
http://1964js.com/shaders/fragment.shader

**Comment by vgturtle127** [comment]
So the file on the website is what we should put in the repo, then?

There is no return after gl_FragColor, is that also correct?

And I'm also assuming that the int variations on this file are correct and the commented out lines are not correct? Or at least are being investigated or something? Just wanna make sure. :laughing:

**Comment by schibo** [comment]
> So the file on the website is what we should put in the repo, then?

It's ugly code, but yes please :)

> There is no return after gl_FragColor, is that also correct?

No return after the function is ok.

> And I'm also assuming that the int variations on this file are correct and the commented out lines are not correct? Or at least are being investigated or something? Just wanna make sure. :laughing:

uBlendColor was being loaded wrong by the emulator (as I recall) and it caused things to look worse, but it is/was being investigated.

**Comment by vgturtle127** [comment]
Alright, just wanted to make sure. :smile:
