### ISSUE TITLE
Can we remove the 1964js.pyc file?

### ISSUE THREAD

**Issue by vgturtle127** [schibo/1964js#9]
I was wondering if there is any reason why somebody couldn't compile this for themselves?

Just curious. Merely trying to make sure we keep the repo clean. :smile:

**Comment by schibo** [comment]
Ya, pyc files should be removed from the repository and added to .gitignore. They are compiled on the back-end production server and persist there. https://github.com/github/gitignore/blob/master/Python.gitignore seems to have a .gitignore boilerplate.

**Comment by vgturtle127** [comment]
Alright. I will start working on a combo .gitignore. :smile:
